<?php

define('GTM_ADMIN_LISTING_PAGE_URL', 'admin/content/gtm-admin');
define('GTM_ADMIN_LISTING_PAGE_ACCOUNT_URL', 'admin/content/gtm-admin');
define('GTM_ADMIN_TAG_URL', 'admin/content/gtm-admin/tag');
define('GTM_ADMIN_WORKSPACE_URL', 'admin/content/gtm-admin/workspace');
define('GTM_ADMIN_DEFAULT_TRIGGER_ID', 2147479553);

// TODO: optimize load point.
module_load_include('inc', 'gtm_admin', 'includes/gtm_admin.google');

/**
 * Implements hook_menu().
 */
function gtm_admin_menu() {

  // Config page
  $items['admin/config/search/gtm-admin-config'] = [
    'title' => 'GTM admin config',
    'file' => 'includes/gtm_admin.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['gtm_admin_config_form'],
    'access callback' => TRUE,
  ];

  // Global list, from accounts
  $items[GTM_ADMIN_LISTING_PAGE_URL] = [
    'title' => 'GTM admin list',
    'file' => 'includes/gtm_admin.pages.inc',
    'page callback' => 'gtm_admin_page',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  ];

  // Tag add (edit) form
  $items[GTM_ADMIN_TAG_URL . '/manage/%/%/%/%'] = [
    'title' => 'GTM admin tag management',
    'file' => 'includes/gtm_admin.actions.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['gtm_admin_tag_form', 5, 6, 7, 8],
    'access callback' => TRUE,
  ];

  // Tag delete form
  $items[GTM_ADMIN_TAG_URL . '/delete/%/%/%/%'] = [
    'title' => 'GTM admin tag management',
    'file' => 'includes/gtm_admin.actions.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['gtm_admin_tag_delete_form', 5, 6, 7, 8],
    'access callback' => TRUE,
  ];

  // Publish container form
  $items[GTM_ADMIN_WORKSPACE_URL . '/publish/%/%/%'] = [
    'title' => 'GTM admin tag management',
    'file' => 'includes/gtm_admin.actions.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['gtm_admin_workspace_publish_form', 5, 6, 7],
    'access callback' => TRUE,
  ];

  // List for account
  $items[GTM_ADMIN_LISTING_PAGE_ACCOUNT_URL . '/%'] = [
    'title' => 'GTM admin list for account',
    'file' => 'includes/gtm_admin.pages.inc',
    'page callback' => 'gtm_admin_account_page',
    'page arguments' => [3],
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  ];

  // List for container
  $items[GTM_ADMIN_LISTING_PAGE_ACCOUNT_URL . '/%/%'] = [
    'title' => 'GTM admin list for container',
    'file' => 'includes/gtm_admin.pages.inc',
    'page callback' => 'gtm_admin_container_page',
    'page arguments' => [3, 4],
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  ];

  // Container versions
  $items[GTM_ADMIN_LISTING_PAGE_ACCOUNT_URL . '/versions/%/%'] = [
    'title' => 'GTM admin list for versions',
    'file' => 'includes/gtm_admin.pages.inc',
    'page callback' => 'gtm_admin_versions_page',
    'page arguments' => [4, 5],
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  ];

  // Workspace page is unnecessary.
  $items[GTM_ADMIN_LISTING_PAGE_ACCOUNT_URL . '/%/%/%'] = [
    'title' => 'GTM admin list for workspace',
    'file' => 'includes/gtm_admin.pages.inc',
    'page callback' => 'gtm_admin_workspace_page',
    'page arguments' => [4, 5, 6],
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

// API function - get account list
// TODO: Check if we need this function at all?
function gtm_admin_get_account_list() {
  $service = _gtm_admin_get_google_gtm_service();
  if (!$service) {
    return $service;
  }

  $accounts = $service->accounts->listAccounts();

  $return = [];
  foreach ($accounts->getAccount() as $account) {
    $return[$account->getAccountId()] = $account->getName();
  }

  return $return;
}

// API function - get container list
// TODO: Check if we need this function at all?
function gtm_admin_get_container_list($account_id) {
  $service = _gtm_admin_get_google_gtm_service();
  if (!$service) {
    return $service;
  }

  $params = ['accounts' => $account_id];
  $params_string = _gtm_admin_get_parent_string($params);
  $containers = $service->accounts_containers->listAccountsContainers($params_string);

  $return = [];
  foreach ($containers->getContainer() as $container) {
    $return[$container->getContainerId()] = $container->getName() . ' (' . $container->getPublicId() . ')';
  }

  return $return;
}

// API function - get workspace list
function gtm_admin_get_container_content($account_id, $container_id, $publish_actions = TRUE) {
  module_load_include('inc', 'gtm_admin', 'includes/gtm_admin.pages');

  return gtm_admin_container_page($account_id, $container_id, $publish_actions);
}

// API function - get workspace list
function gtm_admin_get_versions_content($account_id, $container_id) {
  module_load_include('inc', 'gtm_admin', 'includes/gtm_admin.pages');

  return gtm_admin_versions_page($account_id, $container_id);
}

// API function - get workspace list
// TODO: Looks like we don't need this function at all?
// Problem is - workspace id changes after publishing
function gtm_admin_get_workspace_list($account_id, $container_id) {
  $service = _gtm_admin_get_google_gtm_service();
  if (!$service) {
    return $service;
  }
  $params = [
    'accounts' => $account_id,
    'containers' => $container_id,
  ];
  $params_string = _gtm_admin_get_parent_string($params);
  $workspaces = $service->accounts_containers_workspaces->listAccountsContainersWorkspaces($params_string);

  $return = [];

  foreach ($workspaces->getWorkspace() as $workspace) {
    $return[$workspace->getWorkspaceId()] = $workspace->getName();
  }

  return $return;
}
